### ISSUE TITLE
imgurfetcher doesn't do well with albums.

### ISSUE THREAD

**Issue by ElDeveloper** [SantiagoTorres/bg_daemon#3]
I tried changing the name of the subreddit to `spaceporn` and the following exception showed up:

``` python
yoshikivazquezbaeza:~$ background_daemon.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/background_daemon.py", line 4, in <module>
    __import__('pkg_resources').run_script('bg-daemon==0.0.1', 'background_daemon.py')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 517, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 1443, in run_script
    exec(script_code, namespace, namespace)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bg_daemon-0.0.1-py2.7.egg/EGG-INFO/scripts/background_daemon.py", line 240, in <module>

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bg_daemon-0.0.1-py2.7.egg/EGG-INFO/scripts/background_daemon.py", line 196, in poll

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bg_daemon-0.0.1-py2.7.egg/EGG-INFO/scripts/background_daemon.py", line 128, in update

  File "build/bdist.macosx-10.6-intel/egg/bg_daemon/fetchers/imgurfetcher.py", line 131, in query
  File "build/bdist.macosx-10.6-intel/egg/bg_daemon/fetchers/imgurfetcher.py", line 233, in _select_image
AttributeError: GalleryAlbum instance has no attribute 'width'
```

This may be a shot in the dark, but I think fetcher needs to verify that it is indeed looking at an image not an album.

**Comment by SantiagoTorres** [comment]
Hmmm, I wouldn't be surprised if this was true. Do you have the address of the gallery so I can repeat the bug?

**Comment by ElDeveloper** [comment]
No, I don't have the URL handy, from looking at the log file it doesn't
seem like it saved that information. I'm sure you can try with any
album.
